import type { NextPage } from "next";
import Head from "next/head";
import {
  AppleLoginButton,
  GoogleLoginButton,
} from "../components/SocialLoginButton";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <AppleLoginButton />
        <GoogleLoginButton />
      </main>
    </div>
  );
};

export default Home;
