import { Button } from "@mui/material";
import axios from "axios";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const [info, setInfo] = useState({
    error: false,
    message: "click the above button",
  });
  const onClickHandler = async () => {
    try {
      const res = await axios("/api/passport-apple");
      await console.log(res);
    } catch (e: any) {
      setInfo({
        error: true,
        message: e.response.data as string,
      });
    }
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Button variant="contained" onClick={onClickHandler}>
          get Method
        </Button>
        <p style={{ margin: 5 }}>{info.error && "error"}</p>
        <p style={{ margin: 5 }}>{info.message}</p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
